create table Person (
                        id int generated by default as identity primary key,
                        name varchar(100) not null,
                        age int,
                        email varchar(100)
);

insert into Person(name,age,email) values ('Tom', 25, 'tom@mail.ru');
insert into Person(name,age,email) values ('Bob', 12, 'bob@mail.ru');
insert into Person(name,age,email) values ('Sam', 36, 'sam@mail.ru');